### PR TITLE
Add V2 version of checkstyle

### PR DESCRIPTION
**Pull request by NandeeshKamathPayPay**
Added checkstyle which will be used by payments module to generate checkstyle violation report.

### CODE REVIEW

**Review by harspras — APPROVED** [review]
LGTM 👍

**Comment by ttamari** [comment]
The content looks the same as the existing checkstyle file, what is the difference?

**Comment by NandeeshKamathPayPay** [comment]
> The content looks the same as the existing checkstyle file, what is the difference?

I believe it's for keeping a seperate file just got payments team so that it can be updated when required. Please correct me if wrong. :bowing_man: @harspras

**Review by tommy810pp — APPROVED** [review]
LGTM 👍

**Comment by harspras** [comment]
@ttamari We will be updating this checkstyle later to remove javadoc settings, change line settings according to payment team's policies. For now, there is no change as such.

**Review by ttamari — APPROVED** [review]

**Pull request merged**
